name: whisper
services:
  whisper:
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4096M
    container_name: whisper_en
    volumes:
      - /home/zen/docker/model:/model
      - /home/zen/docker/yt-dlp:/data
      - /home/zen/github/WhisperInDocker:/app
    environment:
      - root=/data
      - language=English
      - pattern=webm
      - model=large
      - location=/model
    image: whisper:latest