# .github/workflows/release.yml
name: tar_releaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "publish*"
    # branches: [ "master" ]

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  dockerbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: go
        run: go build -o srt main.go
      - name: pwd
        run: pwd
      - name: build
        run: docker build -t whisper:latest .
      - name: saveSpace
        run: rm -rf /opt/hostedtoolcache
      - name: export
        run: docker save whisper:latest -o whisper.tar
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/whisper.tar
          asset_name: whisper
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is Whisper.tar image"