# .github/workflows/release.yml
name: tar_releaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "public*"
    # branches: [ "master" ]

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  dockerbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: go
        run: go build -o srt main.go
      - name: release
        run: |
          time_var=$(date +"%Y%m%d-%H%M%S")
          gh release create $time_var --generate-notes
          gh release upload $time_var ${{ github.workspace }}/srt
        env:
          GH_TOKEN: ${{ github.token }}