# .github/workflows/release.yml
name: xz_releaser

on:
  pull_request:
  push:
    # run only against tags
#    tags:
#      - "*"
    branches: [ "master" ]

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  dockerbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: go
        run: go build -o srt main.go
      - name: pwd
        run: pwd
      - name: build
        run: docker build -t whisper:latest /home/runner/work/WhisperInDocker/WhisperInDocker
      - name: saveSpace
        run: rm -rf /opt/hostedtoolcache
      - name: export
        run: docker save whisper:latest | xz --threads=0 -9e --memlimit-compress=0 > whisper.tar.xz
      - name: split
        run: zip -r -s 500M whisper.zip whisper.tar.xz
      - name: check
        run: ls -ahl ${{ github.workspace }}
      - name: Upload z01
        uses: actions/upload-artifact@v4
        with:
          name: z01
          path: ${{ github.workspace }}/whisper.z01
          compression-level: 9 # max compression
      - name: Upload z02
        uses: actions/upload-artifact@v4
        with:
          name: z02
          path: ${{ github.workspace }}/whisper.z02
          compression-level: 9 # max compression
      - name: Upload z03
        uses: actions/upload-artifact@v4
        with:
          name: z03
          path: ${{ github.workspace }}/whisper.z03
          compression-level: 9 # max compression
      - name: Upload z04
        uses: actions/upload-artifact@v4
        with:
          name: z04
          path: ${{ github.workspace }}/whisper.z04
          compression-level: 9 # max compression
      - name: Upload z05
        uses: actions/upload-artifact@v4
        with:
          name: z05
          path: ${{ github.workspace }}/whisper.z05
          compression-level: 9 # max compression
      - name: Upload z06
        uses: actions/upload-artifact@v4
        with:
          name: z06
          path: ${{ github.workspace }}/whisper.z06
          compression-level: 9 # max compression
      - name: Upload z07
        uses: actions/upload-artifact@v4
        with:
          name: zip07
          path: ${{ github.workspace }}/whisper.z07
          compression-level: 9 # max compression
      - name: Upload z08
        uses: actions/upload-artifact@v4
        with:
          name: zip08
          path: ${{ github.workspace }}/whisper.z08
          compression-level: 9 # max compression
      - name: Upload z09
        uses: actions/upload-artifact@v4
        with:
          name: zip09
          path: ${{ github.workspace }}/whisper.z09
          compression-level: 9 # max compression
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: zip
          path: ${{ github.workspace }}/whisper.zip
          compression-level: 9 # max compression
